# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "computers", :force => true do |t|
    t.column "bought", :date
  end

  create_table "file_locations", :force => true do |t|
    t.column "fileinfo_id",   :integer, :limit => 10
    t.column "location_type", :string,  :limit => 64
    t.column "location_id",   :integer, :limit => 10
    t.column "path",          :string,  :limit => 1024
    t.column "filename",      :string,  :limit => 256
  end

  create_table "fileinfos", :force => true do |t|
    t.column "sha2",     :string,  :limit => 64
    t.column "filesize", :integer, :limit => 3
  end

  create_table "harddisks", :force => true do |t|
    t.column "name",          :string,  :limit => 64
    t.column "description",   :string,  :limit => 256
    t.column "location_type", :string,  :limit => 64
    t.column "location_id",   :integer, :limit => 10
  end

  create_table "locations", :force => true do |t|
    t.column "type",          :string,  :limit => 32
    t.column "name",          :string,  :limit => 64
    t.column "description",   :string,  :limit => 256
    t.column "located",       :string,  :limit => 64
    t.column "location_type", :string,  :limit => 32
    t.column "location_id",   :integer, :limit => 10
  end

  create_table "optical_media", :force => true do |t|
    t.column "name",        :string, :limit => 64
    t.column "description", :string, :limit => 256
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

end
